### ISSUE TITLE
"uploading your picture" stuck

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1492]
I've actually had this issue for a good while now since Maplibre change:
I upload an image and it continues showing the orange text box as if it's still uploading.

Even if i close the object's dialog and open it again
 The image gets uploaded correctly. It just continues showing that message.

Chrome android

![Screenshot_20230703_135850_Chrome](https://github.com/pietervdvn/MapComplete/assets/1010226/d429b572-276d-47bf-8a78-dde8fd9bb6a9)

**Comment by pietervdvn** [comment]
Yeah, I know. I'm ignoring this until an SDK for geovisio is available.

**Comment by thibaultmol** [comment]
Also, very annoying bug i'm running into. let me know if you want me to spin this into a seperate issue @pietervdvn :
Take an object with two images (that have been uploaded a while ago).
Remove the first one.
And right after, upload a new one. 
That second image shows up in the interface, but isn't actually added as an osm tag to the object.

**Comment by pietervdvn** [comment]
I think that the top issue is fixed, but the second one might still be around.

**Comment by thibaultmol** [comment]
Yeah, first issue I've not encountered for months now. 
There is still some weirdness if you happen to minimize the website as it's uploading. And maybe the rotation bug is still there (if you upload and then you rotate your phone it resets. not sure, would have to test)

But the the second issue i described about multiple images weirdness is def still there

**Comment by thibaultmol** [comment]
closing this in favor of separate image related upload issues when they arrise
