### ISSUE TITLE
GRB: CORS Missing allow origin

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1641]
CSP related, I assume you haven't fixed it yet, so I'm just making this issue to keep it on the todo list:
![image](https://github.com/pietervdvn/MapComplete/assets/1010226/85786022-e82c-4bf6-b615-347909b59c85)

**Comment by pietervdvn** [comment]
In this case, the other server does not give permission to use this data on our website. I assume that you are using `dev`? `dev.mapcomplete.org` does _not_ have permission, but `mapcomplete.org` does.

If you want this fixed, ask Gplv in the OSM-buildings chat channel to also allow `dev.mapcomplete.org`

**Comment by thibaultmol** [comment]
so this is fixed now. But now we get this:
![image](https://github.com/pietervdvn/MapComplete/assets/1010226/4487ebd7-fd46-4156-8602-d1c4e2f78f08)
https://dev.mapcomplete.org/grb.html?z=16&lat=50.980105108273364&lon=3.3102179773585476

**Comment by pietervdvn** [comment]
Seems that the upstream server emits a warning in case of an empty response. They are ignored by MC, but I've asked GPLV to fix this as well.

However, one should still see the correct data on the map.

**Comment by pietervdvn** [comment]
All these issues are fixed by now.
