### ISSUE TITLE
Add an icon

### ISSUE THREAD

**Issue by bryceco** [pietervdvn/MapComplete#223]
If I use "Add to Home Screen" on my iPhone I expect to have a pretty icon show up, but instead I get a thumbnail of the webpage.

**Comment by pietervdvn** [comment]
Normally, the icon should be delivered. Could you please share which phone you are using, which browser and attach a screenshot?

**Comment by bryceco** [comment]
Safari on iPhone

**Comment by bryceco** [comment]
![image](https://user-images.githubusercontent.com/279734/111360200-b279e680-8649-11eb-80d2-d9a29c472d9b.png)

**Comment by bryceco** [comment]
![image](https://user-images.githubusercontent.com/279734/111360483-084e8e80-864a-11eb-8d2f-22ccda6968e2.jpeg)

**Comment by pietervdvn** [comment]
Ok, seems like safari has a different system and I need to add

```<link rel="shortcut icon" href="">    <link rel="apple-touch-icon" href="">```

**Comment by bryceco** [comment]
I don't know if it's possible but it would also be nice if it suggested MapComplete as the name instead of the theme name (unless you expect people to have separate bookmarks for every theme)￼:

￼![image](https://user-images.githubusercontent.com/279734/111362331-e0602a80-864b-11eb-9d64-d5b048b071df.png)

**Comment by pietervdvn** [comment]
Yes, I expect people either to have multiple bookmarks or to bookmark the index page. MapComplete is set up to have a strong 'theme'-presence, the fact that it is mapcomplete is not relevant for the user.

I deployed a new version on my testsite which should fix your issue. Please make sure that the version number indicates "0.5.13" (if not, reload until it does) then try bookmarking this version - it should give the correct icon: https://pietervdvn.github.io/MapComplete/bookcases

**Comment by bryceco** [comment]
That didn't fix the icon (I verified the version number). 

Also, even though in Safari it displays the theme name in English when I save it it switches to Dutch.￼￼

**Comment by pietervdvn** [comment]
Can you try again on the same link? It should show version 0.5.14

**Comment by bryceco** [comment]
Fixed!

**Comment by pietervdvn** [comment]
Great! Did it show the bookcase-icon or the generic MapComplete-icon (which is an OSM-logo with a plus in the looking glass)?

**Comment by bryceco** [comment]
![image](https://user-images.githubusercontent.com/279734/111512731-4d87c480-870d-11eb-8484-05323d13cf91.jpeg)

**Comment by pietervdvn** [comment]
Ah, perfect!
